"""Headless HTTP client for Midtown Comics."""

from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor
from urllib.parse import urljoin

import requests
from bs4 import BeautifulSoup

from .credentials import load_session_cookies, save_session
from .parsers import (
    parse_order_detail,
    parse_orders,
    parse_preview_items,
    parse_product_body,
    parse_release_date,
    parse_search,
    parse_wishlist,
)

BASE_URL = "https://www.midtowncomics.com"


class MidtownClient:
    def __init__(self, base_url: str = BASE_URL):
        self.base_url = base_url.rstrip("/")
        self.session = requests.Session()
        self.session.headers.update({"User-Agent": "midtown-comics-cli/0.1"})
        self._load_cookies()

    def _load_cookies(self) -> None:
        for cookie in load_session_cookies():
            kwargs = {
                "name": cookie["name"],
                "value": cookie.get("value", ""),
                "path": cookie.get("path", "/"),
                "secure": bool(cookie.get("secure", False)),
            }
            if cookie.get("domain"):
                kwargs["domain"] = cookie["domain"]
            if cookie.get("expires", -1) not in (-1, None):
                kwargs["expires"] = cookie["expires"]
            self.session.cookies.set(**kwargs)

    def _save_cookies(self) -> None:
        save_session([
            {
                "name": cookie.name,
                "value": cookie.value,
                "domain": cookie.domain,
                "path": cookie.path,
                "secure": cookie.secure,
                "expires": cookie.expires if cookie.expires is not None else -1,
            }
            for cookie in self.session.cookies
        ])

    def login(self) -> None:
        """Log in with the stored credentials through headless Chromium.

        Midtown's form requires a reCAPTCHA v3 token generated by page
        JavaScript, so a plain HTTP form post cannot authenticate.
        """
        from .remote_auth import run_automated_login

        run_automated_login()
        self.session.cookies.clear()
        self._load_cookies()

    @staticmethod
    def _looks_like_login(html: str) -> bool:
        soup = BeautifulSoup(html, "html.parser")
        return bool(soup.find("input", attrs={"name": "txtPassword"}))

    def _is_login_response(self, response: requests.Response) -> bool:
        return response.url.rstrip("/").endswith("/login") or self._looks_like_login(response.text)

    def _post_authenticated(self, path: str) -> requests.Response:
        """POST an account endpoint, logging in once automatically if the session expired."""
        url = urljoin(self.base_url, path)
        response = self.session.post(url, timeout=30)
        response.raise_for_status()
        if self._is_login_response(response):
            self.login()
            response = self.session.post(url, timeout=30)
            response.raise_for_status()
            self._require_authenticated(response)
        return response

    def orders(self) -> list[dict]:
        response = self._post_authenticated("/ord-contents")
        orders = parse_orders(response.text, self.base_url)
        for order in orders:
            detail = self.session.post(
                urljoin(self.base_url, "/ord-info"),
                data={"od_id": order["order_number"], "is_archived": "0"},
                timeout=30,
            )
            detail.raise_for_status()
            if not self._looks_like_login(detail.text):
                order["items"] = parse_order_detail(detail.text, self.base_url)
        self._save_cookies()
        return orders

    def wishlist(self) -> list[dict]:
        response = self._post_authenticated("/wsh-contents")
        result = parse_wishlist(response.text, self.base_url)
        self._save_cookies()
        return result

    def preorders(self) -> list[dict]:
        """Items not yet released: pending items of regular orders plus Previews pre-orders."""
        pending = [
            {
                "source": "order",
                "order_number": order["order_number"],
                "order_date": order.get("date", ""),
                "product_id": item.get("product_id", ""),
                "title": item.get("title", ""),
                "quantity": item.get("quantity", 1),
                "unit_price": item.get("unit_price"),
                "release_date": self._release_date(item.get("product_id", "")),
                "status": item["status"],
                "product_url": item.get("product_url", ""),
            }
            for order in self.orders()
            for item in order.get("items", [])
            if item.get("status") == "Pending"
        ]
        previews = parse_preview_items(self._post_authenticated("/mpi-contents").text, self.base_url)
        return pending + previews

    def _release_date(self, product_id: str) -> str:
        if not product_id:
            return ""
        response = self.session.get(urljoin(self.base_url, f"/product/{product_id}"), timeout=30)
        response.raise_for_status()
        return parse_release_date(response.text)

    def search(self, query: str, per_page: int = 100, page: int = 1, include_preorders: bool = False, show_out_of_stock: bool = False) -> list[dict]:
        # Same as the site: the "Include Pre-orders" (rel) and "Show out of stock" (os)
        # filters are only sent when enabled.
        params: dict[str, str | int] = {"q": query, "pp": per_page, "pj": page}
        if include_preorders:
            params["rel"] = 1
        if show_out_of_stock:
            params["os"] = 1
        response = self.session.get(urljoin(self.base_url, "/search"), params=params, timeout=30)
        response.raise_for_status()
        products = parse_search(response.text, self.base_url)
        lazy = [product for product in products if not product["availability"]]
        # ponytail: 8 parallel requests; fine for <=100 results per page.
        with ThreadPoolExecutor(max_workers=8) as pool:
            bodies = list(pool.map(self._product_body, [product["product_id"] for product in lazy]))
        lazy_bodies = dict(zip((product["product_id"] for product in lazy), bodies))
        return [
            {**product, **{key: value for key, value in lazy_bodies.get(product["product_id"], {}).items() if value not in (None, "")}}
            for product in products
        ]

    def _product_body(self, product_id: str) -> dict:
        """Fetch the price/cart block the search page loads asynchronously for a card."""
        response = self.session.post(
            urljoin(self.base_url, "/search-load-product-body"),
            data={"pr_parentid": product_id, "pr_id": product_id},
            timeout=30,
        )
        response.raise_for_status()
        return parse_product_body(response.text)

    def _require_authenticated(self, response: requests.Response) -> None:
        if self._is_login_response(response):
            raise RuntimeError(
                "Midtown session is not authenticated even after logging in with the stored "
                "credentials; run `midtown auth browser-login --remote` to log in manually"
            )
